Algoritmo "areaQuadrado"
// Disciplina   : Programação e algoritimos
// Professor   : Cintia Pinho
// Autor(a)    : Mariany Santos Bim
// Data atual  : 01/03/2021
// Descrição   : calcular area do quadrado

Var
base, area:real


Inicio
escreval("digite a base do quadrado: ")
leia(base)
escreval("digite a base do quadrado: ")
leia(base)
area <- base*base

escreval("area do triangulo",area,"m²")


Fimalgoritmo