Algoritmo "semnome"
// Descrição   :identifica se voce pode competir
// Autor(a)    : Mariany Santos Bim
// Data atual  : 08/06/2021
Var
idade: inteiro
altura:real

Inicio
escreval("qual sua altura?")
leia(altura)
escreval("qual sua idade?")
leia(idade)

se((altura>1.75)e (idade>18)) entao
 escreval("voce podera competir")
 
 senao
 escreval("voce nao podera competir")
fimse

Fimalgoritmo