Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   :desvendar se éum numero par ou impar
// Autor(a)    : Mariany Santos Bim
// Data atual  : 08/06/2021
Var
num:inteiro


Inicio
escreval ("Digite um valor")
leia(num)

se((num mod 2)=0)entao
escreval("este numero é par")

senao
escreval("este numero é impar")
fimse



Fimalgoritmo