Algoritmo "imparesLAÇO"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/08/2021
Var
 cont,result:inteiro


Inicio
PARA cont de 101 ate 200 passo 2 faca
 escreval(cont)
 result<- result+cont
 fimpara


Fimalgoritmo