Algoritmo "areaTriangulo"

// Disciplina   : Programação e algoritimos
// Professor   : Cintia Pinho
// Autor(a)    : Mariany Santos Bim
// Data atual  : 01/03/2021
// Descrição   :calcular area triangulo
Var
base, altura, area:real

Inicio
 escreval("digite a base do triangulo: ")
 leia(base)
 escreval("digite a altura do triangulo")
 leia(altura)
 area <- base*altura/2
 escreval("area do retangulo: ", area)




Fimalgoritmo