Algoritmo "areaRetangulo"
// Disciplina   : Programação e algoritimos
// Professor   : Cintia Pinho
// Autor(a)    : Mariany Santos Bim
// Data atual  : 01/03/2021
// Descrição   : calcular area do retangulo
Var
base, altura, area:real

Inicio
escreval("digite a base do retangulo: ")
leia (base)
escreval("digite a altura do retangulo: ")
 leia(altura)
 area <- base*altura
 
 escreval("area do retangulo: ",area,"m²")

Fimalgoritmo