Algoritmo "conversãofahrenheit"
// Descrição   : conversão de celsius para fahrenheit
// Autor(a)    : Mariany Santos Bim
// Data atual  : 15/03/2021
Var
 c, f, celsius:real


Inicio
Escreval("Este programa converte fahrenheit em celsius")
escreval("digite a temperatura de agora nos EUA: ")
 leia(f)
 
 celsius <- (f - 32) * 5/9
 escreval (f, "graus fahrenheit, convertidos em celsius ficara: ",celsius,"graus celsius")
Fimalgoritmo