Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/08/2021
Var
resp:caracter


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
repita
 escreval("digite o nome da melhor escola de Ribeirão Pires")
 leia(resp)


ate((resp="ETEC MCM")ou( resp="etec mcm"))

Fimalgoritmo